import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    lineHeight: 1.5,
  },
  title: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    marginBottom: 20,
    textAlign: "center",
    color: "#1B365D",
  },
  subtitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    marginTop: 16,
    marginBottom: 8,
    color: "#1B365D",
  },
  row: {
    flexDirection: "row",
    marginBottom: 4,
  },
  label: {
    fontFamily: "Helvetica-Bold",
    width: 160,
  },
  value: {
    flex: 1,
  },
  paragraph: {
    marginBottom: 8,
  },
  footer: {
    marginTop: 30,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#D1D5DB",
    fontSize: 9,
    color: "#6B7280",
  },
});

type InfoSheetProps = {
  landlordName: string;
  tenantName: string;
  propertyAddress: string;
  tenancyType: string;
  tenancyStart: string;
  depositAmount: string;
  depositScheme: string;
  depositRef: string;
  servedDate: string;
};

export function InfoSheetPDF({
  landlordName,
  tenantName,
  propertyAddress,
  tenancyType,
  tenancyStart,
  depositAmount,
  depositScheme,
  depositRef,
  servedDate,
}: InfoSheetProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>
          Prescribed Information — Tenancy Deposit
        </Text>
        <Text style={styles.paragraph}>
          In accordance with the Housing Act 2004 (as amended), the following
          prescribed information is provided to the tenant.
        </Text>

        <Text style={styles.subtitle}>Property Details</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Property Address:</Text>
          <Text style={styles.value}>{propertyAddress}</Text>
        </View>

        <Text style={styles.subtitle}>Parties</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Landlord:</Text>
          <Text style={styles.value}>{landlordName}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Tenant:</Text>
          <Text style={styles.value}>{tenantName}</Text>
        </View>

        <Text style={styles.subtitle}>Tenancy Details</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Tenancy Type:</Text>
          <Text style={styles.value}>{tenancyType}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Tenancy Start Date:</Text>
          <Text style={styles.value}>{tenancyStart}</Text>
        </View>

        <Text style={styles.subtitle}>Deposit Information</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Deposit Amount:</Text>
          <Text style={styles.value}>
            {depositAmount ? `£${depositAmount}` : "Not specified"}
          </Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Protection Scheme:</Text>
          <Text style={styles.value}>{depositScheme || "Not specified"}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Scheme Reference:</Text>
          <Text style={styles.value}>{depositRef || "Not specified"}</Text>
        </View>

        <Text style={styles.subtitle}>Tenant Rights</Text>
        <Text style={styles.paragraph}>
          The tenant has the right to apply to the county court if the landlord
          fails to comply with the deposit protection requirements. The tenant
          may recover up to three times the deposit amount if the deposit is not
          properly protected or the prescribed information is not served within
          30 days.
        </Text>

        <Text style={styles.footer}>
          This document was served on {servedDate}. Generated by LandlordShield.
        </Text>
      </Page>
    </Document>
  );
}
